"""抓猪插件纯领域规则。"""

from .economy import (
    COOK_COIN_REWARDS,
    COOK_EXPERIENCE_REWARDS,
    EAT_EXPERIENCE_REWARDS,
    FOOD_BASE_VALUES,
    FOOD_RARITY_NAMES,
    UPGRADE_DISPLAY_NAMES,
    FoodAttributes,
    StoreProduct,
    adjusted_cooking_weights,
    build_store_products,
    generate_food_attributes,
    item_product_by_name,
    recipe_affinity,
    stable_recipe_factor,
    upgrade_type_by_name,
)
from .enums import AssetKind, ConsentStatus, FatProfile, Rarity, ReceiptSendStatus, TemplateScope
from .gameplay import (
    CATCH_COIN_REWARDS,
    CATCH_EXPERIENCE_REWARDS,
    ITEM_DEFINITIONS,
    ITEMS_BY_ID,
    LEVEL_THRESHOLDS,
    PIG_BASE_VALUES,
    PIG_RARITY_NAMES,
    ItemDefinition,
    LevelProgress,
    PigAttributes,
    generate_pig_attributes,
    item_by_id,
    item_by_name,
    level_progress,
)
from .models import AssetSelector, CommandIdentity, ScopeKey

__all__ = [
    "AssetKind",
    "AssetSelector",
    "CATCH_COIN_REWARDS",
    "CATCH_EXPERIENCE_REWARDS",
    "COOK_COIN_REWARDS",
    "COOK_EXPERIENCE_REWARDS",
    "CommandIdentity",
    "ConsentStatus",
    "FatProfile",
    "FoodAttributes",
    "FOOD_BASE_VALUES",
    "FOOD_RARITY_NAMES",
    "EAT_EXPERIENCE_REWARDS",
    "ITEM_DEFINITIONS",
    "ITEMS_BY_ID",
    "ItemDefinition",
    "LEVEL_THRESHOLDS",
    "LevelProgress",
    "PIG_BASE_VALUES",
    "PIG_RARITY_NAMES",
    "PigAttributes",
    "Rarity",
    "ReceiptSendStatus",
    "ScopeKey",
    "StoreProduct",
    "TemplateScope",
    "UPGRADE_DISPLAY_NAMES",
    "adjusted_cooking_weights",
    "build_store_products",
    "generate_food_attributes",
    "generate_pig_attributes",
    "item_by_id",
    "item_by_name",
    "item_product_by_name",
    "level_progress",
    "recipe_affinity",
    "stable_recipe_factor",
    "upgrade_type_by_name",
]
